services:

  activemq:
    image: rmohr/activemq:latest
    container_name: mars_broker
    ports:
      - "8161:8161"  


  simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars_simulator
    ports:
      - "8080:8080"

  rest_poller:
    build: ./
    container_name: mars_rest_poller
    restart: always
    depends_on:
      - simulator
      - activemq
    environment:
      - PYTHONUNBUFFERED=1

