

services:
  # ---------------------------------------------------------
  # 1. IL MESSAGE BROKER (ActiveMQ)
  # ---------------------------------------------------------
  activemq:
    image: rmohr/activemq:latest  # Un'immagine Docker leggera e affidabile per ActiveMQ
    container_name: mars_broker
    ports:
      - "61616:61616" # Porta OpenWire (standard Java)
      - "61613:61613" # Porta STOMP (quella che usiamo noi in Python!)
      - "8161:8161"   # Porta per la Dashboard grafica (Web Console)

  # ---------------------------------------------------------
  # 2. IL SIMULATORE DEL PROFESSORE
  # ---------------------------------------------------------
  simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars_simulator
    ports:
      - "8080:8080"

  # ---------------------------------------------------------
  # 3. IL TUO MICROSERVIZIO DI INGESTIONE REST
  # ---------------------------------------------------------
  rest_poller:
    build: ./backend/sensors_server
    container_name: mars_rest_poller
    depends_on:
      - simulator
      - activemq
    environment:
      - PYTHONUNBUFFERED=1
      - BROKER_HOST=activemq
      - BROKER_PORT=61613
      - SIMULATOR_URL=http://simulator:8080
  # ---------------------------------------------------------
  # 4. IL MOTORE DI AUTOMAZIONE (Chi riceve i dati)
  # ---------------------------------------------------------
  automation_engine:
    build: ./backend/acturators_server
    container_name: mars_automation_engine
    depends_on:
      - activemq
    environment:
      - PYTHONUNBUFFERED=1
      - BROKER_HOST=activemq
      - BROKER_PORT=61613